import { Exo, Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/component/header";
import Footer from "@/component/footer";

// Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
});

// Exo font
const exo = Exo({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-exo",
});

export const metadata = {
  title: "Home ETU Academy",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png", // path to your logo file in the public folder
    apple: "/logo.png", // optional: for Apple devices
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${exo.variable}`}>
      <body
        className="antialiased font-sans"
        style={{ fontFamily: "var(--font-exo)" }} // Default to Exo
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
